In [522]:
import numpy as np
import pandas as pd

In [523]:
features = pd.read_csv('./dataset and all/training_set_features.csv')
features.head(5)

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [524]:
features.shape

(26707, 36)

In [525]:
features.isnull().sum()

respondent_id                      0
xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
hhs_geo_region                     0
census_msa                         0
household_adults                 249
household_children               249
employment_industry            13330
employment_occupation          13470
dtype: int64

In [526]:
feat = features.drop(columns=['employment_occupation','employment_industry','hhs_geo_region','census_msa','health_insurance','race','marital_status','household_adults','household_children'])
feat.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,opinion_xyz_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,education,sex,income_poverty,rent_or_own,employment_status
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,2.0,2.0,1.0,2.0,55 - 64 Years,< 12 Years,Female,Below Poverty,Own,Not in Labor Force
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,4.0,4.0,2.0,4.0,35 - 44 Years,12 Years,Male,Below Poverty,Rent,Employed
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,4.0,1.0,2.0,18 - 34 Years,College Graduate,Male,"<= $75,000, Above Poverty",Own,Employed
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,5.0,5.0,4.0,1.0,65+ Years,12 Years,Female,Below Poverty,Rent,Not in Labor Force
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,2.0,3.0,1.0,4.0,45 - 54 Years,Some College,Female,"<= $75,000, Above Poverty",Own,Employed

In [527]:
feat = pd.get_dummies(feat,columns=['sex','income_poverty','employment_status','education','rent_or_own','age_group'],dtype = int)
feat.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education_< 12 Years,education_College Graduate,education_Some College,rent_or_own_Own,rent_or_own_Rent,age_group_18 - 34 Years,age_group_35 - 44 Years,age_group_45 - 54 Years,age_group_55 - 64 Years,age_group_65+ Years
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,0,0,1,0,0,0,0,1,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0,0,0,0,1,0,1,0,0,0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,1,0,1,0,0,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0,0,0,0,1,0,0,0,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0,0,1,1,0,0,0,1,0,0

In [528]:
feat.isnull().sum()

respondent_id                                  0
xyz_concern                                   92
xyz_knowledge                                116
behavioral_antiviral_meds                     71
behavioral_avoidance                         208
behavioral_face_mask                          19
behavioral_wash_hands                         42
behavioral_large_gatherings                   87
behavioral_outside_home                       82
behavioral_touch_face                        128
doctor_recc_xyz                             2160
doctor_recc_seasonal                        2160
chronic_med_condition                        971
child_under_6_months                         820
health_worker                                804
opinion_xyz_vacc_effective                   391
opinion_xyz_risk                             388
opinion_xyz_sick_from_vacc                   395
opinion_seas_vacc_effective                  462
opinion_seas_risk                            514
opinion_seas_sick_from_vacc                  537
sex_Female                                     0
sex_Male                                       0
income_poverty_<= $75,000, Above Poverty       0
income_poverty_> $75,000                       0
income_poverty_Below Poverty                   0
employment_status_Employed                     0
employment_status_Not in Labor Force           0
employment_status_Unemployed                   0
education_12 Years                             0
education_< 12 Years                           0
education_College Graduate                     0
education_Some College                         0
rent_or_own_Own                                0
rent_or_own_Rent                               0
age_group_18 - 34 Years                        0
age_group_35 - 44 Years                        0
age_group_45 - 54 Years                        0
age_group_55 - 64 Years                        0
age_group_65+ Years                            0
dtype: int64

In [529]:
targets = pd.read_csv('./dataset and all/training_set_labels.csv')
targets.columns

Index(['respondent_id', 'xyz_vaccine', 'seasonal_vaccine'], dtype='object')

In [530]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X = feat.drop(columns = ['respondent_id','xyz_concern','doctor_recc_xyz','opinion_xyz_vacc_effective','opinion_xyz_risk', 'opinion_xyz_sick_from_vacc'])
y = targets.drop(columns = ['respondent_id','xyz_vaccine'])

merged = pd.concat([X,y],ignore_index = True, axis = 1)
merged.columns = list(X.columns) + list(y.columns)

merged = merged.dropna()

X_train,X_test,y_train,y_test = train_test_split(merged.drop(columns = ['seasonal_vaccine']),merged['seasonal_vaccine'],test_size = 0.3,random_state = 42)
model = LogisticRegression(max_iter = 1000)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7793481396019614

In [531]:
from sklearn.metrics import roc_auc_score

pred = model.predict_proba(X_test)
print(roc_auc_score(y_test,pred[:,1], average = 'macro'))

0.8515321734218745

In [532]:
X = feat.drop(columns = ['respondent_id','doctor_recc_seasonal','opinion_seas_vacc_effective','opinion_seas_risk','opinion_seas_sick_from_vacc'])
y = targets.drop(columns = ['respondent_id','seasonal_vaccine'])

merged = pd.concat([X,y],ignore_index = True, axis = 1)
merged.columns = list(X.columns) + list(y.columns)

merged = merged.dropna()

X_train,X_test,y_train,y_test = train_test_split(merged.drop(columns = ['xyz_vaccine']),merged['xyz_vaccine'],test_size = 0.3,random_state = 42)
model = LogisticRegression(max_iter = 1000)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8298580944106574

In [533]:
pred = model.predict_proba(X_test)
print(roc_auc_score(y_test,pred[:,1], average = 'macro'))

0.830816832032025

In [534]:
test_features = pd.read_csv('./dataset and all/test_set_features.csv')
print(test_features.shape)

(26708, 36)

In [535]:
test_feat = test_features.drop(columns=['employment_occupation','employment_industry','hhs_geo_region','census_msa','health_insurance','race','marital_status','household_adults','household_children'])
test_feat = pd.get_dummies(test_feat,columns=['sex','income_poverty','employment_status','education','rent_or_own','age_group'],dtype = int)

test_feat.head(5)

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education_< 12 Years,education_College Graduate,education_Some College,rent_or_own_Own,rent_or_own_Rent,age_group_18 - 34 Years,age_group_35 - 44 Years,age_group_45 - 54 Years,age_group_55 - 64 Years,age_group_65+ Years
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0,1,0,0,1,0,1,0,0,0
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,0,0
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0,1,0,1,0,0,0,0,1,0
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,0,1
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0,0,0,1,0,0,1,0,0,0

In [536]:
#for xyz
X_test = test_feat.drop(columns = ['respondent_id'])
X_train = feat.drop(columns = ['respondent_id'])
y_train = targets.drop(columns = ['respondent_id','seasonal_vaccine'])

merged = pd.concat([X_train,y_train],ignore_index = True, axis = 1)
merged.columns = list(X_train.columns) + list(y_train.columns)

merged = merged.dropna()
X_test = X_test.dropna()

#print(X_test.isnull().sum())

model.fit(merged.drop(columns = ['xyz_vaccine']),merged['xyz_vaccine'])
pred = model.predict_proba(X_test)
pred_xyz = pred[:,1]

In [537]:
#for seasonal
X_test = test_feat.drop(columns = ['respondent_id'])
X_train = feat.drop(columns = ['respondent_id'])
y_train = targets.drop(columns = ['respondent_id','xyz_vaccine'])

merged = pd.concat([X_train,y_train],ignore_index = True, axis = 1)
merged.columns = list(X_train.columns) + list(y_train.columns)

merged = merged.dropna()
X_test = X_test.dropna()

#print(X_test.isnull().sum())

model.fit(merged.drop(columns = ['seasonal_vaccine']),merged['seasonal_vaccine'])
pred = model.predict_proba(X_test)
pred_seasonal = pred[:,1]

In [538]:
print(pred_seasonal.size)
print(pred_xyz.size)

22988
22988

In [539]:
ids = [i for i in range(26707,(26707+22988))]

result = pd.DataFrame({'respondent_id':list(ids), 'xyz_vaccine':list(pred_xyz), 'seasonal_vaccine':list(pred_seasonal)})
result.to_csv('./submission.csv',index=False)